### ISSUE TITLE
kwargs with single *

### ISSUE THREAD

**Issue by theturboturnip** [mysticfall/bpystubgen#1]
The generated bpy stubs are great, except for a syntax error in a generated file that prevents e.g. mypy from working with them.

In `bpy_extras/anim_utils.pyi`, kwargs are specified for `bake_action` and `bake_action_objects` with a single *.
This conflicts with the previous *args declaration, and causes a syntax error.
I think to fix this the tool just needs to emit `**kwargs` everywhere.

Example:
```python
def bake_action(obj: bpy.types.Object, *args, action: bpy.types.Action, frames: typing.Iterable[int], *kwargs) -> bpy.types.Action:
  ...

def bake_action_objects(object_action_pairs: typing.Any, *args, frames: typing.Iterable[int], *kwargs) -> typing.Sequence[bpy.types.Action]:
  """

  A version of :func:`bake_action_objects_iter` that takes frames and returns the output.

  """
  ...
```

**Comment by theturboturnip** [comment]
Upon further inspection, the problem is likely here
https://github.com/mysticfall/bpystubgen/blob/1c0762bfefcac322619d5e7d29b04afcb5250eea/bpystubgen/directives.py#L274

I can try to make a PR fixing this

**Comment by mysticfall** [comment]
Fixed now, thanks to your PR. Great work!
